/**
 * @typedef {{
 *   name?: string;
 *   description?: string;
 *   range?: string | boolean;
 *   values?: Map<string | number | boolean, string>;
 *   noValueDetails?: boolean;
 * }} NodeInfo
 */

/** @type {Map<string, NodeInfo>} */ export const NODE_INFO = new Map([
	['Root', { name: '', description: 'This is the root of the document.\nIt is not represented as an actual node in the file.' }],
	['`A2Ts`', { name: 'Anchor Link **A**lt **T**ext', range: false }],
	['`AACb`', { name: 'Export GIF **A**nimation **C**rop', description: 'Crop individual frames when exporting as animated GIF.', range: false }],
	['`AADb`', { name: 'Export GIF **A**nimation **D**iff', description: 'Only include diffs between frames when exporting as animated GIF.', range: false }],
	['`AGMb`', { description: 'Seen this set to `false` in one file, but it\'s usually `true`; seems to have no impact on rendering.', values: new Map([[true, 'normal (TODO)']]) }],
	['`ALNi`', { description: 'Appears to be some sort of randomly-generated ID', range: false }],
	['`ALSv`', { name: '**S**ymbol Instance', description: 'References a [`MSTv`] symbol definition with a matching [`MSNi`] ID.' }],
	['`ALTs`', { name: '**A**nchor **L**ink **T**arget', range: false }],
	['`ANNi`', { name: '**An**imation **N**umber of Frames', description: 'Number of frames of animation to generate for the animation-type symbol (this generates a smooth transition using [`ANRi`], [`ASCf`], [`ASOi`], [`AEOi`], [`ANXf`], and [`ANYf`]).', range: '`1`..inf' }],
	['`ANRi`', { name: '**An**imation **R**otation', description: 'Number of degrees of clockwise rotation to apply to an animation-type symbol. Uses a **signed** 32-bit value. Negative numbers are counter-clockwise.', range: '`-360`..`360` (degrees)' }],
	['`ANXf`', { name: '**An**imation **X** Shift', description: 'Amount of x translation (pixels) to apply to an animation-type symbol. Uses a **signed** 32-bit value.', range: false }],
	['`ANYf`', { name: '**An**imation **Y** Shift', description: 'Amount of y translation (pixels) to apply to an animation-type symbol. Uses a **signed** 32-bit value.', range: false }],
	['`APLb`', {}],
	['`APSb`', {}], // something to do with the exported palette?
	['`ASCf`', { name: '**A**nimation **Sc**aling', description: 'Scaling to apply to an animation-type symbol', range: '`0`..`250` (percent)' }],
	['`ASOi`', { name: '**A**nimation **S**tart **O**pacity', description: 'Initial opacity for animation-type symbol.', range: '`0` (transparent) .. `1000` (opaque)' }],
	['`AEOi`', { name: '**A**nimation **E**nd **O**pacity', description: 'Final opacity for animation-type symbol. Defaults to 1000.', range: '`0` (transparent) .. `1000` (opaque)' }],
	['`ASTi`', { range: true }],
	['`ATEb`', { name: '**A**u**t**o-**E**nlarge', values: new Map([[false, 'Fixed width, wrap text.'], [true, 'Adapt width to fit text content, no soft wrapping.']]) }],
	['`ATKb`', { name: '**A**u**t**o-**K**ern', description: 'Apply kerning based on character shape.', range: false }],
	['`ATMv`', { name: 'Symbol **T**ransform **M**atrix', description: 'Unclear what this matrix is for; it only includes translation, not rotation/scale/skew. Possibly a legacy value? Prefer using [`MTXv`] for the transformation.' }],
	['`ATSb`', {}],
	['`BANi`', { name: '**B**rush **An**gle', range: '`0`..`359` (degrees); `0` = horizontal, `90` = vertical, increasing clockwise' }],
	['`BASi`', { name: '**B**rush **As**pect', range: '`0` (flat) .. `1000` (round)' }],
	['`BAZv`', { name: '**B**e**z**ier Sub-Point', description: 'These sub-points are spaced equally along the bezier curve (TODO: by distance or by t-value?), and give details about varying pressure and speed of the pen.' }],
	['`BBKi`', { name: '**B**rush **B**lac**k**ness', range: '`0`..`1000` (per mille)' }],
	['`BBLi`', {}],
	['`BCLi`', { name: '**B**rush **C**o**l**our', range: '`0x00000000`..`0xffffffff`', description: 'ABGR format colour.' }],
	['`BEHv`.`BCLi`', { name: '**B**ackground **C**o**l**our', range: '`0x00000000`..`0xffffffff`', description: 'ABGR format colour.' }],
	['`BPLv`.`BCMi`', { name: '**B**rush Tip **C**olouring **M**ode', description: 'Used to decide individual tip colours if [`BNTi`] > `1`', values: new Map([[0, 'random'], [1, 'uniform'], [2, 'complementary'], [3, 'hue'], [4, 'shadow (tips nearer the bottom have higher blackness)']]) }],
	['`BEHv`.`BCMi`', { name: '**B**ackground **C**olour Hover', description: 'A BGRA colour for the background of highlighted menu items.', range: '`0x00000000`..`0xffffffff`' }],
	['`BCNi`', { name: '**B**rush **C**o**n**centration', range: '`0`..`1000` (per mille)' }],
	['`BDIi`', { name: '**B**rush **Di**ameter', range: '`0`..inf (pixels)' }],
	['`BEEi`', {}],
	['`BEFi`', { name: '**B**rush **E**dge **F**unction', values: new Map([[0, 'none'], [1, 'white neon'], [2, 'harsh wet'], [3, 'smooth neon'], [4, 'wavy gravy'], [5, 'white neon edge']]) }],
	['`BEHv`', { name: '**Beh**aviour', description: [
		'Used for popup menus. Possibly for other behaviours too.',
		'',
		'For popup menus, [`TRNs`] contains the menu definition in the format:',
		'',
		'```text',
		'{{"Item 1","link","target",{{"Nested 1","nested link","nested target",{}}{"Nested 2","","",{{"Sub-nested","","",{}}}}}}{"Item 2","","",{}}}',
		'```',
	].join('\n') }],
	['`BETi`', { name: '**Be**haviour **T**ype', values: new Map([[9, 'popup menu']]) }],
	['`BEVv`', { name: '**Be**haviour List' }],
	['`BFBi`', { name: '**Br**ush **F**eed**b**ack', values: new Map([[0, 'none'], [1, 'brush'], [2, 'background']]) }],
	['`BFRi`', { name: '**Br**ush **F**low **R**ate', range: '`0`..`1000` (per mille)' }],
	['`BGCi`', { name: '**B**ack**g**round **C**olour', range: '`0x00000000`..`0xffffffff`', description: 'ABGR format colour.' }],
	['`BIAb`', { name: '**B**rush **I**s **A**nti-Aliased', range: false }],
	['`BKGb`', {}],
	['`BLDi`', { name: '**Bl**en**d** Mode', values: new Map([
		[2, 'multiply'],
		[3, 'difference'],
		[4, 'overlay'],
		[5, 'screen'],
		[7, 'disolve'],
		[8, 'linear burn'],
		[9, 'darken'],
		[10, 'lighten'],
		[11, 'hue'],
		[12, 'saturation'],
		[13, 'color'],
		[14, 'luminosity'],
		[17, 'invert'],
		[18, 'linear dodge'],
		[19, 'vivid light'],
		[20, 'linear light'],
		[21, 'pin light'],
		[22, 'hard mix'],
		[25, 'erase'],
		[29, 'tint'],
		[30, 'average'],
		[31, 'negation'],
		[32, 'exclusion'],
		[33, 'hard light'],
		[34, 'soft light'],
		[35, 'fuzzy light'],
		[36, 'color dodge'],
		[37, 'color burn'],
		[38, 'inverse color dodge'],
		[39, 'inverse color burn'],
		[40, 'soft dodge'],
		[41, 'soft burn'],
		[42, 'reflect'],
		[43, 'glow'],
		[44, 'freeze'],
		[45, 'heat'],
		[46, 'additive'],
		[47, 'subtractive'],
		[48, 'interpolation'],
		[49, 'stamp'],
		[50, 'xor'],
		[51, 'red'],
		[52, 'green'],
		[53, 'blue'],
		[54, 'subtract'],
	]) }],
	['`BLSf`', { name: '**B**ase**l**ine **S**hift', values: new Map([[-10, 'subscript'], [0, 'normal'], [10, 'superscript']]) }],
	['`BMMi`', { name: '**B**rush **M**ax Count', range: '`1`..`31`', description: 'UI limit on number of brush tips?' }],
	['`BMSi`', { name: '**B**rush **M**in **S**ize', description: 'Lower bound on rendered tip size when varying (e.g. due to sensitivity), as a proportion of the brush size.', range: '`1`..`1000` (per mille)' }],
	['`BNTi`', { name: '**Br**ush **N**umber of **T**ips', range: '`1`..`5`' }],
	['`BOAf`', { name: '**Bo**unds', description: 'Width to fit text to, if [`TFTi`] is `1`.', range: false }],
	['`BOCi`', { name: '**Bo**rder **C**olour', description: 'An ABGR colour for the popup menu border.' }],
	['`BOLb`', { name: '**Bol**d', values: new Map([[true, 'begin bold'], [false, 'end bold']]) }],
	['`BOSi`', { name: '**Bo**rder **S**ize', description: 'Size (in pixels) of the popup menu border.', range: false }],
	['`BOTf`', { name: '**Bot**tom', description: 'Distance (pixels) from top of container to bottom of entity.', range: false }],
	['`BPLv`', { name: '**B**rush **P**roperty **L**ist' }],
	['`BRPi`', { name: '**Br**ush **P**lacement', values: new Map([[0, 'inside'], [1, 'middle'], [2, 'outside']]) }],
	['`BRTi`', { name: '**Br**ush **T**ype', values: new Map([[0, 'natural'], [1, 'simple']]) }],
	['`BSEi`', { name: '**B**rush **S**oft **E**dges', range: '`0`..`1000` (per mille)' }],
	['`BSFi`', { name: '**B**rush **S**oft Edges **F**unction', values: new Map([[0, 'bell curve'], [1, 'linear']]) }],
	['`BSHi`', { name: '**B**rush **Sh**ape', values: new Map([[0, 'square'], [1, 'circle']]) }],
	['`BSLf`', { description: 'Possibly related to hand-drawn curves? (TODO)' }],
	['`BSMi`', { name: '**B**rush Tip **S**pacing **M**ode', values: new Map([
		[0, 'random'],
		[1, 'diagonal - tips are arranged top-left to bottom-right, spaced equally'],
		[2, 'circular - first tip is in centre, surrounded by other tips placed at a fixed distance and equally spaced angles (if only 2 tips, they are placed diagonally)'],
	]) }],
	['`BSPi`', { name: '**B**rush **Sp**acing', description: 'Space between individual stamps of the brush image along the path, as a fraction of the brush size.', range: '`0`..inf (per mille)' }],
	['`BTBi`', { name: '**B**rush **T**exture **B**lend', range: '`0`..`1000` (per mille)' }],
	['`BTEi`', { name: '**B**rush **T**exture **E**dge', range: '`0`..`1000` (per mille)' }],
	['`BTSi`', { name: '**B**rush **T**ip **S**pacing', description: 'Distance from centre of tips to outermost tips, as a fraction of the brush size', range: '`0`..inf (percent)' }],
	['`BZCi`', { name: '**B**e**z**ier Sub-Points **C**ount', description: 'Number of [`BAZv`] nodes (may also be `1` if there are no nodes).', range: false }],
	['`BZLv`', { name: '**B**e**z**ier Sub-Points **L**ist' }],
	['`CATs`', { name: '**Cat**egory', noValueDetails: true }],
	['`CBAi`', { name: '**C**ell **B**ackground (Slice) **A**ttachment', values: new Map([[0, 'fixed'], [1, 'scroll']]) }],
	['`CBHi`', { name: '**C**ell **B**ackground (Slice) **H**orizontal Position', values: new Map([[0, 'left'], [1, 'center'], [2, 'right'], [3, 'value ([`CHVi`])']]) }],
	['`CBRi`', { name: '**C**ell **B**ackground (Slice) **R**epeat', values: new Map([[0, 'no-repeat'], [1, 'repeat-both'], [2, 'repeat-x'], [3, 'repeat-y']]) }],
	['`CBTb`', { description: 'Appears to be `true` if [`TSLi`] is `2` (i.e. slice is "background").', range: false }],
	['`CBUs`', { name: '**C**ell **B**ackground **U**RL', description: 'URL (starting `file://`) of a background image to use when exporting as HTML, or a blank string.', range: false }],
	['`CBVi`', { name: '**C**ell **B**ackground (Slice) **V**ertical Position', values: new Map([[0, 'top'], [1, 'center'], [2, 'bottom'], [3, 'value ([`CVVi`])']]) }],
	['`CDAi`', { name: 'HTML Page **A**lignment', values: new Map([[0, 'left'], [1, 'center'], [2, 'right']]) }],
	['`CDMv`', {}],
	['`CDTs`', { description: 'A timestamp in `yyyyMMddHHmmss` format.', range: false }],
	['`CELv`', { name: 'Animation **Cel**l' }],
	['`CFTs`', { name: '**F**ont **T**ypeface', noValueDetails: true }],
	['`CHOf`', { name: '**Ch**aracter **O**ffset', description: 'Offset (in pixels) along path to begin text.', range: false }],
	['`CHVi`', { name: '**C**ell **H**orizontal **V**alue', description: 'Used if [`CBHi`] is `3`. Otherwise this is always set to `0xffffffff`', range: false }],
	['`CLLb`', { name: '**C**o**l**our **L**ocked', range: false }],
	['`CLLv`', { name: 'Animation **C**e**l**l **L**ist' }],
	['`CLMb`', { name: '**C**o**l**our **M**apped', values: new Map([[true, 'colour is mapped to value of [`BCLi`]'], [false, 'colour is defined by [`FCLi`]']]) }],
	['`CLPi`', { name: 'Export Scale **P**ropotion', description: 'Used to calculate [`XSZi`] and [`YSZi`] if [`CNSb`] is `true` and [`CLSb`] is `true`.', range: '`2`..`200` (percent)' }],
	['`CLRi`', { name: '**C**o**l**ou**r** Mode', values: new Map([[0, 'indexed'], [1, 'RGB'], [2, 'RGBA']]) }],
	['`CLSb`', { name: 'Export **S**cale Constrained', values: new Map([
		[false, '[`XSZi`] and [`YSZi`] are specified by the user directly. Export aspect ratio is not preserved.'],
		[true, '[`XSZi`] and [`YSZi`] are calculated from [`CLPi`] and the image size. Export aspect ratio is preserved.'],
	]) }],
	['`CLTb`', { name: '**C**o**l**our **T**ransparent', range: false }],
	['`CNSb`', { name: 'Export **S**cale', description: 'Note: this value is never `false`; `false` is implied by its absence.', values: new Map([[true, 'Rescale to [`XSZi`] x [`YSZi`] when exporting. See also [`CLSb`].']]) }],
	['`CPSv`', { name: '**C**ontrol **P**oint**s**' }],
	['`CPDi`', { name: 'Menu Item **C**ell **P**a**d**ding', range: false }],
	['`CPTv`', { name: '**C**ontrol **P**oin**t**' }],
	['`CRVb`', { name: 'Is **C**u**rv**e', values: new Map([[true, 'line is a curve'], [false, 'line is straight (points are forced to be colinear)']]) }],
	['`CSHi`', { name: '**C**olour **Sh**adow', description: 'An ABGR colour for the popup menu border shadow.' }],
	['`CSMb`', { name: 'HTML **CS**S **M**enus', description: '"Use CSS for Popup Menus".', range: false }],
	['`CSPi`', { name: 'Menu Item **C**ell **Sp**acing', range: false }],
	['`CTYi`', { name: '**C**ontrol Point **Ty**pe', description: 'Grab handle config controlled by `type` in JavaScript. Appears to control the colour of the handle.', values: new Map([[0, 'default (yellow)'], [1, 'defaultInverted (blue)']]) }],
	['`CVVi`', { name: '**C**ell **V**ertical **V**alue', description: 'Used if [`CBVi`] is `3`. Otherwise this is always set to `0xffffffff`', range: false }],
	['`CXBb`', { description: 'Observed in all Fireworks CS4 files, not seen in Fireworks 8 files. Always seems to be `false`.', values: new Map([[false, 'unknown']]) }],
	['`DCEv` "`AngleSoftness`"', { description: 'Used by "Glow", "Inner Bevel", "Inset Emboss", "Outer Bevel", "Raised Emboss" filters.', range: true }],
	['`DCEv` "`BevelContrast`"', { description: 'Used by "Glow", "Inner Bevel", "Inner Glow", "Inset Emboss", "Outer Bevel", "Raised Emboss" filters.', range: true }],
	['`DCEv`', { name: '**D**i**c**tionary **E**ntry', description: 'A key-value pair with multiple possible value types. Contains a [`DCKs`] and exactly one other child node with type [`DCVs`], [`GPLv`], or [`GDTv`].\n\nThe observed entities broken down by key are:' }],
	['`DCEv` "`BevelType`"', { description: 'Used by "Glow", "Inner Bevel", "Inset Emboss", "Outer Bevel", "Raised Emboss" filters.', values: new Map([
		['0', 'inner bevel'],
		['1', 'outer bevel'],
		['2', 'raise emboss'],
		['3', 'inset emboss'],
		['4', 'glow effect'],
	]) }],
	['`DCEv` "`BevelWidth`"', { description: 'Used by "Glow", "Inner Bevel", "Inset Emboss", "Outer Bevel", "Raised Emboss" filters.', range: true }],
	['`DCEv` "`Blendmode`"', { description: 'Used by "Color Fill" filter.\n\nThe blend mode to use when applying the solid colour fill. Note that some modes (such as "darken") can be set in the UI, but immediately revert to "normal". Also several of these modes render identically, and are not consistent with the layer blend modes.', values: new Map([
		['0', 'normal'],
		['2', 'color burn'],
		['3', 'luminosity'],
		['4', 'hard light'],
		['5', 'inverse color dodge'],
		['8', 'lighten'],
		['9', 'multiply'],
		['10', 'color dodge'],
		['12', 'reflect'],
		['13', 'glow'],
		['14', 'freeze'],
		['18', 'soft light'],
		['19', 'negation'],
		['21', 'hue'],
		['22', 'saturation'],
		['30', 'average'],
		['31', 'green'],
		['32', 'red'],
		['33', 'exclusion'],
		['35', 'difference'],
		['36', 'soft dodge'],
		['37', 'inverse color burn'],
		['39', 'soft burn'],
		['40', 'overlay'],
		['42', 'subtract'],
		['43', 'interpolation'],
		['44', 'stamp'],
		['45', 'xor'],
		['46', 'invert'],
		['47', 'tint'],
		['48', 'erase'],
		['51', 'heat'],
		['53', 'additive'],
	]) }],
	['`DCEv` "`ButtonState`"', { description: 'Used by "Glow", "Inner Bevel", "Inset Emboss", "Outer Bevel", "Raised Emboss" filters.', values: new Map([
		['0', 'up'],
		['1', 'over'],
		['2', 'down'],
		['3', 'hit'],
	]) }],
	['`DCEv` "`Color`"', { description: 'Used by "Color Fill" filter.\n\nA colour in "#rrggbb" format', range: false }],
	['`DCEv` "`Dict`"', { description: 'Used by "Photoshop Live Effects" filter. Always "10". Possibly a version indicator?', range: true }],
	['`DCEv` "`DownBlendColor`"', { description: 'Used by "Glow", "Inner Bevel", "Inset Emboss", "Outer Bevel", "Raised Emboss" filters.\n\nA colour in "#rrggbbaa" format to apply when button is in the "down" state.', range: false }],
	['`DCEv` "`EdgeThreshold`"', { description: 'Used by "Glow", "Inner Bevel", "Inset Emboss", "Outer Bevel", "Raised Emboss" filters.\n\nAlpha threshold for detected edges. "Glow" uses a value of `1`; all other filter types use a value of "0".', range: '`0` (fully transparent) .. `1` (fully opaque)' }],
	['`DCEv` "`EffectIsVisible`"', { values: new Map([['true', 'effect is applied'], ['false', 'effect is not applied']]) }],
	['`DCEv` "`EffectMoaID`"', { values: new Map([
		['{7fe61102-6ce2-11d1-8c76000502701850}', 'Bevel'],
		['{a7944db8-6ce2-11d1-8c76000502701850}', 'Drop Shadow'],
		['{5600f702-774c-11d3-baad0000861f4d01}', 'Inner Shadow'],
		['{b90c950e-64df-11d8-aaf2000a9582f7d4}', 'Solid Shadow'],
		['{2ba87123-8220-11d3-baad0000861f4d01}', 'Inner Glow'],
		['{dd54adc0-a279-11d3-b92a000502f3fdbe}', 'Color Fill'],
		['{d04ef8c1-71b4-11d1-8c8200a024cdc039}', 'Auto Levels'],
		['{d04ef8c2-71b5-11d1-8c8200a024cdc039}', 'Levels'],
		['{3439b08e-1923-11d3-9bde00e02910d580}', 'Curves'],
		['{3439b08d-1922-11d3-9bde00e02910d580}', 'Hue/Saturation'],
		['{3439b08c-1921-11d3-9bde00e02910d580}', 'Brightness/Contrast'],
		['{d2541291-70d6-11d1-8c8000a024cdc039}', 'Invert'],
		['{2932d5a2-ca48-11d1-8561000502701850}', 'Convert to Alpha'],
		['{fc7093f1-f95c-11d0-8be200a024cdc039}', 'Find Edges'],
		['{f1cfce41-718e-11d1-8c8200a024cdc039}', 'Blur'],
		['{538016b6-ffd6-418f-a10c590e6ee841ae}', 'Motion Blur'],
		['{d1c33142-2ad8-4215-a39fc5d934c8fc0c}', 'Radial Blur'],
		['{94dbd663-9b2e-44bf-8064ab6efdd2d327}', 'Zoom Blur'],
		['{d04ef8c0-71b3-11d1-8c8200a024cdc039}', 'Gaussian Blur'],
		['{f1cfce42-718e-11d1-8c8200a024cdc039}', 'Blur More'],
		['{f1cfce44-718e-11d1-8c8200a024cdc039}', 'Unsharp Mask'],
		['{c20952b1-fc76-11d0-8be700a024cdc039}', 'Sharpen'],
		['{1f2f2591-9db7-11d1-8cad00a024cdc039}', 'Sharpen More'],
		['{e4c0f4bc-c0a3-4cb3-b3513822027e4d9f}', 'Add Noise'],
		['{ff84d00c-4494-11d8-a072000a9582f7d4}', 'Clouds'],
		['{d2e7769c-6349-11d8-b0e9000a9595f34e}', 'Difference Clouds'],
		['{d810e821-f86b-11d0-6563413465646d41}', 'Marble (Eye Candy 4000 LE plugin?)'],
		['{d810e821-f86b-11d0-656341346564694e}', 'Bevel Boss (Eye Candy 4000 LE plugin?)'],
		['{d810e821-f86b-11d0-6563413465646d54}', 'Motion Trail (Eye Candy 4000 LE plugin?)'],
		['{d810e821-f86b-11d0-7371473173676544}', 'Edges (Alien Skin Splat LE plugin?)'],
		['{8eeadf50-9efe-11da-a7460800200c9a66}', 'Photoshop Live Effects Special Fill'],

		['{d810e821-f86b-11d0-466c747241636345}', 'Accented Edges (obsolete / plugin? - seen in Fireworks MX file)'],
		['{d810e821-f86b-11d0-466c7472416e6753}', 'Angled Strokes (obsolete / plugin? - seen in Fireworks MX file)'],
		['{d810e821-f86b-11d0-466c747243727368}', 'Crosshatch (obsolete / plugin? - seen in Fireworks MX file)'],
		['{d810e821-f86b-11d0-466c747244726b53}', 'Dark Strokes (obsolete / plugin? - seen in Fireworks MX file)'],
		['{d810e821-f86b-11d0-466c7472496e6b4f}', 'Ink Outlines (obsolete / plugin? - seen in Fireworks MX file)'],
		['{d810e821-f86b-11d0-466c747253707420}', 'Spatter (obsolete / plugin? - seen in Fireworks MX file)'],
		['{d810e821-f86b-11d0-466c747253707253}', 'Sprayed Strokes (obsolete / plugin? - seen in Fireworks MX file)'],
		['{d810e821-f86b-11d0-466c7472536d6965}', 'Sumi-e (obsolete / plugin? - seen in Fireworks MX file)'],
		['{d810e821-f86b-11d0-466c74724273526c}', 'Bas Relief (obsolete / plugin? - seen in Fireworks MX file)'],
		['{d810e821-f86b-11d0-466c747243686c43}', 'Chalk && Charcoal (obsolete / plugin? - seen in Fireworks MX file)'],
		['{d810e821-f86b-11d0-466c74724368726d}', 'Chrome (obsolete / plugin? - seen in Fireworks MX file)'],
		['{d810e821-f86b-11d0-466c7472436e7443}', 'Conté Crayon (obsolete / plugin? - seen in Fireworks MX file)'],
		['{d810e821-f86b-11d0-466c74724e745072}', 'Note Paper (obsolete / plugin? - seen in Fireworks MX file)'],
		['{d810e821-f86b-11d0-466c747250687463}', 'Photocopy (obsolete / plugin? - seen in Fireworks MX file)'],
		['{d810e821-f86b-11d0-466c7472506c7374}', 'Plaster (obsolete / plugin? - seen in Fireworks MX file)'],
		['{d810e821-f86b-11d0-466c74725274636c}', 'Reticulation (obsolete / plugin? - seen in Fireworks MX file)'],
		['{d810e821-f86b-11d0-466c747253746d70}', 'Stamp (obsolete / plugin? - seen in Fireworks MX file)'],
		['{d810e821-f86b-11d0-466c747254726e45}', 'Torn Edges (obsolete / plugin? - seen in Fireworks MX file)'],
		['{d810e821-f86b-11d0-466c747257747250}', 'Water Paper (obsolete / plugin? - seen in Fireworks MX file)'],
		['{d810e821-f86b-11d0-466c7472436c7250}', 'Colored Pencil (obsolete / plugin? - seen in Fireworks MX file)'],
		['{d810e821-f86b-11d0-466c747244727942}', 'Dry Brush (obsolete / plugin? - seen in Fireworks MX file)'],
		['{d810e821-f86b-11d0-466c7472466c6d47}', 'Film Grain (obsolete / plugin? - seen in Fireworks MX file)'],
		['{d810e821-f86b-11d0-466c74724e476c77}', 'Neon Glow (obsolete / plugin? - seen in Fireworks MX file)'],
		['{d810e821-f86b-11d0-466c7472506e7444}', 'Paint Daubs (obsolete / plugin? - seen in Fireworks MX file)'],
		['{d810e821-f86b-11d0-466c7472506c744b}', 'Palette Knife (obsolete / plugin? - seen in Fireworks MX file)'],
		['{d810e821-f86b-11d0-466c7472506c7357}', 'Plastic Wrap (obsolete / plugin? - seen in Fireworks MX file)'],
		['{d810e821-f86b-11d0-466c747252676850}', 'Rough Pastels (obsolete / plugin? - seen in Fireworks MX file)'],
		['{d810e821-f86b-11d0-466c7472536d6453}', 'Smudge Stick (obsolete / plugin? - seen in Fireworks MX file)'],
		['{d810e821-f86b-11d0-466c747253706e67}', 'Sponge (obsolete / plugin? - seen in Fireworks MX file)'],
		['{d810e821-f86b-11d0-466c7472556e6472}', 'Underpainting (obsolete / plugin? - seen in Fireworks MX file)'],
		['{d810e821-f86b-11d0-466c747257747263}', 'Watercolor (obsolete / plugin? - seen in Fireworks MX file)'],
		['{d810e821-f86b-11d0-466c74724372716c}', 'Craquelure (obsolete / plugin? - seen in Fireworks MX file)'],
		['{d810e821-f86b-11d0-466c747247726e20}', 'Grain (obsolete / plugin? - seen in Fireworks MX file)'],
		['{d810e821-f86b-11d0-466c747250746368}', 'Patchwork (obsolete / plugin? - seen in Fireworks MX file)'],
		['{d810e821-f86b-11d0-466c74725478747a}', 'Texturizer (obsolete / plugin? - seen in Fireworks MX file)'],
		['{d810e821-f86b-11d0-466c747244667347}', 'Diffuse Glow (obsolete / plugin? - seen in Fireworks MX file)'],
		['{d810e821-f86b-11d0-466c7472476c7320}', 'Glass (obsolete / plugin? - seen in Fireworks MX file)'],
		['{d810e821-f86b-11d0-466c74724f636e52}', 'Ocean Ripple (obsolete / plugin? - seen in Fireworks MX file)'],
		['{d810e821-f86b-11d0-466c7472476c7745}', 'Glowing Edges (obsolete / plugin? - seen in Fireworks MX file)'],
	]) }],
	['`DCEv` "`EmbossFaceColor`"', { description: 'Used by "Glow", "Inner Bevel", "Inset Emboss", "Outer Bevel", "Raised Emboss" filters.\n\nA colour in "#rrggbbaa" format', range: false }],
	['`DCEv` "`GlowStartDistance`"', { description: 'Used by "Glow", "Inner Bevel", "Inner Glow", "Inset Emboss", "Outer Bevel", "Raised Emboss" filters.', range: true }],
	['`DCEv` "`GlowWidth`"', { description: 'Used by "Glow", "Inner Bevel", "Inner Glow", "Inset Emboss", "Outer Bevel", "Raised Emboss" filters.', range: true }],
	['`DCEv` "`HiliteColor`"', { description: 'Used by "Glow", "Inner Bevel", "Inset Emboss", "Outer Bevel", "Raised Emboss" filters.\n\nA colour in "#rrggbb" format', range: false }],
	['`DCEv` "`HitBlendColor`"', { description: 'Used by "Glow", "Inner Bevel", "Inset Emboss", "Outer Bevel", "Raised Emboss" filters.\n\nA colour in "#rrggbbaa" format to apply when button is in the "hit" (hover) state', range: false }],
	['`DCEv` "`LightAngle`"', { description: 'Used by "Glow", "Inner Bevel", "Inset Emboss", "Outer Bevel", "Raised Emboss" filters.', range: '`0`..`360` (degrees)' }],
	['`DCEv` "`LightDistance`"', { description: 'Used by "Glow", "Inner Bevel", "Inset Emboss", "Outer Bevel", "Raised Emboss" filters.', range: true }],
	['`DCEv` "`MB_filter_preview_tile_size`"', {}],
	['`DCEv` "`MaskSoftness`"', { description: 'Used by "Glow", "Inner Bevel", "Inner Glow", "Inset Emboss", "Outer Bevel", "Raised Emboss" filters.', range: true }],
	['`DCEv` "`Opacity`"', { description: 'Used by "Color Fill" filter.', range: '`0`..`100` (percent)' }],
	['`DCEv` "`OuterBevelColor`"', { description: 'Used by "Glow", "Inner Bevel", "Inner Glow", "Inset Emboss", "Outer Bevel", "Raised Emboss" filters.\n\nA colour in "#rrggbb" format', range: false }],
	['`DCEv` "`ShadowAngle`"', { description: 'Used by "Drop Shadow", "Inner Shadow" filters.', range: '`0`..`360` (degrees)' }],
	['`DCEv` "`ShadowBlur`"', { description: 'Used by "Drop Shadow", "Inner Shadow" filters.', range: true }],
	['`DCEv` "`ShadowColor`"', { description: 'Used by "Drop Shadow", "Glow", "Inner Shadow" filters.\n\nA colour in "#rrggbbaa" or "#rrggbb" format', range: false }],
	['`DCEv` "`ShadowDistance`"', { description: 'Used by "Drop Shadow", "Inner Shadow" filters.', range: true }],
	['`DCEv` "`ShadowType`"', { description: 'Used by "Drop Shadow", "Inner Shadow" filters.', values: new Map([
		['0', 'normal'],
		['1', 'knockout'],
	]) }],
	['`DCEv` "`ShowObject`"', { description: 'Used by "Glow", "Inner Bevel", "Inset Emboss", "Outer Bevel", "Raised Emboss" filters.', range: false }],
	['`DCEv` "`SlopeMultiplier`"', { description: 'Used by "Glow", "Inner Bevel", "Inset Emboss", "Outer Bevel", "Raised Emboss" filters.', range: true }],
	['`DCEv` "`SlopeType`"', { description: 'Used by "Glow", "Inner Bevel", "Inset Emboss", "Outer Bevel", "Raised Emboss" filters.', values: new Map([
		['0', 'flat'],
		['1', 'smooth'],
		['2', 'smooth inverted'],
		['3', 'zigzag'],
		['4', 'zigzag 2'],
		['5', 'ring'],
		['6', 'ruffle'],
	]) }],
	['`DCEv` "`add_noise_amount`"', { description: 'Used by "Add Noise" filter.', range: '`0`..`400` (percent)' }],
	['`DCEv` "`add_noise_use_color`"', { description: 'Used by "Add Noise" filter.', values: new Map([['false', 'use grayscale noise'], ['true', 'use rgb noise']]) }],
	['`DCEv` "`alrtmsg`"', { description: 'Internal data used by Star autoshape.' }],
	['`DCEv` "`alrtmsg`"."`maxmsg`"', { description: 'Internal data used by Star autoshape.', range: false }],
	['`DCEv` "`alrtmsg`"."`minmsg`"', { description: 'Internal data used by Star autoshape.', range: false }],
	['`DCEv` "`angle`"', { description: 'Used by "Solid Shadow" filter.', range: '`0`..`360` (degrees)' }],
	['`DCEv` "`arrowLength`"', { description: 'Internal data used by Arrow autoshape.', range: false }],
	['`DCEv` "`arrowTip`"', { description: 'Internal data used by Arrow autoshape.', range: false }],
	['`DCEv` "`arrowWidth`"', { description: 'Internal data used by Arrow autoshape.', range: false }],
	['`DCEv` "`atMin`"', { description: 'Internal data used by Arrow autoshape.', range: false }],
	['`DCEv` "`awMin`"', { description: 'Internal data used by Arrow autoshape.', range: false }],
	['`DCEv` "`bevelEmboss`"', { description: [
		'Used by "Photoshop Live Effects" filter: "Bevel and Emboss".',
		'',
		'This is an "&"-separated string, for example:',
		'',
		'```text',
		'0&0&0&0&0&75.000000&75.000000&120.000000&30.000000&100.000000&5.000000&0.000000&screen&RGBColor;255.000000;255.000000;255.000000&multiply&RGBColor;0.000000;0.000000;0.000000&softMatte&innerBevel&stampIn&2$$0.000000;0.000000;1$255.000000;255.000000;1&noshape&notexture',
		'```',
		'',
		'Fields:',
		'',
		'1. Unknown (`0` / `1`)',
		'2. Unknown (always `0`)',
		'3. Unknown (always `0`)',
		'4. Unknown (always `0`)',
		'5. Unknown (always `0`)',
		'6. Unknown number',
		'7. Unknown number',
		'8. Angle (`-180.0`..`180.0`)',
		'9. Unknown number (always `30.0`)',
		'10. Depth (`1.0`..`1000.0`)',
		'11. Size (`0.0`..`250.0`)',
		'12. Soften (`0`..`16`)',
		'13. Highlight: "normal" / "screen" / "multiply" / etc.',
		'14. Highlight colour `RGBColor;<r>;<g>;<b>`',
		'15. Shadow: "normal" / "screen" / "multiply" / etc.',
		'16. Shadow colour `RGBColor;<r>;<g>;<b>`',
		'17. Unknown "softMatte" / "preciseMatte"',
		'18. Style "outerBevel" / "innerBevel" / [guessed: "emboss" / "pillowEmboss" / "strokeEmboss"]',
		'19. Unknown "stampIn" / "stampOut"',
		'20. Unknown; always `2$$0.000000;0.000000;1$255.000000;255.000000;1` - maybe colour space related?',
		'21. Unknown; always "noshape"',
		'22. Unknown; always "notexture"',
	].join('\n'), range: false }],
	['`DCEv` "`blue_points`"', { description: 'Used by "Curves" filter.' }],
	['`DCEv` "`brightness_amount`"', { description: 'Used by "Brightness/Contrast" filter.', range: '`-100`..`100` (percent)' }],
	['`DCEv` "`c2y`"', { description: 'Internal data used by Spiral autoshape.', range: false }],
	['`DCEv` "`category`"', { noValueDetails: true }],
	['`DCEv` "`clockwise`"', { description: 'Internal data used by Spiral autoshape.', range: false }],
	['`DCEv` "`cloud_color`"', { description: 'Used by "Clouds" filter.\n\nA colour in "#rrggbb" format', range: false }],
	['`DCEv` "`color`"', { description: 'Used by "Solid Shadow" filter.\n\nA colour in "#rrggbbaa" or "#rrggbb" format', range: false }],
	['`DCEv` "`constants`"', { description: 'Internal data used by Star, Spiral autoshapes.' }],
	['`DCEv` "`constants`"."`maxB`"', { description: 'Internal data used by Spiral autoshape.', range: false }],
	['`DCEv` "`constants`"."`maxNodes`"', { description: 'Internal data used by Star, Polygon autoshapes.', range: false }],
	['`DCEv` "`constants`"."`minB`"', { description: 'Internal data used by Spiral autoshape.', range: false }],
	['`DCEv` "`constants`"."`minNodes`"', { description: 'Internal data used by Star, Polygon autoshapes.', range: false }],
	['`DCEv` "`constants`"."`ppc`"', { description: 'Internal data used by Spiral autoshape.', range: false }],
	['`DCEv` "`contrast_amount`"', { description: 'Used by "Brightness/Contrast" filter.', range: true }],
	['`DCEv` "`corner0`"', { description: 'Internal data used by Rounded Rectangle autoshape.', range: false }],
	['`DCEv` "`corner1`"', { description: 'Internal data used by Rounded Rectangle, Connector Line autoshapes.', range: false }],
	['`DCEv` "`corner2`"', { description: 'Internal data used by Rounded Rectangle, Connector Line autoshapes.', range: false }],
	['`DCEv` "`corner3`"', { description: 'Internal data used by Rounded Rectangle autoshape.', range: false }],
	['`DCEv` "`custData`"', { description: 'Internal data used by Arrow Tool autoshape.' }],
	['`DCEv` "`custData`"."`box`"', { description: 'Internal data used by Arrow Tool autoshape.', range: false }],
	['`DCEv` "`custData`"."`head1`"', { description: 'Internal data used by Arrow Tool autoshape.', range: false }],
	['`DCEv` "`custData`"."`head2`"', { description: 'Internal data used by Arrow Tool autoshape.', range: false }],
	['`DCEv` "`custData`"."`none`"', { description: 'Internal data used by Arrow Tool autoshape.', range: false }],
	['`DCEv` "`custData`"."`tail`"', { description: 'Internal data used by Arrow Tool autoshape.', range: false }],
	['`DCEv` "`dest_high_blue`"', { description: 'Used by "Auto Levels", "Levels" filters.', range: true }],
	['`DCEv` "`dest_high_green`"', { description: 'Used by "Auto Levels", "Levels" filters.', range: true }],
	['`DCEv` "`dest_high_red`"', { description: 'Used by "Auto Levels", "Levels" filters.', range: true }],
	['`DCEv` "`dest_high_rgb`"', { description: 'Used by "Auto Levels", "Levels" filters.', range: true }],
	['`DCEv` "`dest_low_blue`"', { description: 'Used by "Auto Levels", "Levels" filters.', range: true }],
	['`DCEv` "`dest_low_green`"', { description: 'Used by "Auto Levels", "Levels" filters.', range: true }],
	['`DCEv` "`dest_low_red`"', { description: 'Used by "Auto Levels", "Levels" filters.', range: true }],
	['`DCEv` "`dest_low_rgb`"', { description: 'Used by "Auto Levels", "Levels" filters.', range: true }],
	['`DCEv` "`distance`"', { description: 'Used by "Solid Shadow" filter.', range: true }],
	['`DCEv` "`dropShadow`"', { description: [
		'Used by "Photoshop Live Effects" filter: "Drop Shadow".',
		'',
		'This is an "&"-separated string, for example:',
		'',
		'```text',
		'0&75.000000&0&120.000000&0.000000&5.000000&5.000000&74.000000&0&1&multiply&RGBColor;0.000000;0.000000;0.000000&2$$0.000000;0.000000;1$255.000000;255.000000;1',
		'```',
		'',
		'Fields:',
		'',
		'1. Unknown (`0` / `1`)',
		'2. Unknown number (`0.0`..`100.0`)',
		'3. Unknown (always `0`)',
		'4. Angle (`-180.0`..`180.0`)',
		'5. Spread (`0.0`..`100.0`)',
		'6. Unknown number (`1.0`..`250.0`) - matches Size except min is 1.0',
		'7. Size (`0.0`..`250.0`)',
		'8. Unknown (always `0`)',
		'9. Unknown (`0` / `1`)',
		'10. Blend mode ("multiply")',
		'11. Colour `RGBColor;<r>;<g>;<b>`',
		'12. Unknown; always `2$$0.000000;0.000000;1$255.000000;255.000000;1` - maybe colour space related?',
	].join('\n'), range: false }],
	['`DCEv` "`gamma_blue`"', { description: 'Used by "Auto Levels", "Levels" filters.', range: true }],
	['`DCEv` "`gamma_green`"', { description: 'Used by "Auto Levels", "Levels" filters.', range: true }],
	['`DCEv` "`gamma_red`"', { description: 'Used by "Auto Levels", "Levels" filters.', range: true }],
	['`DCEv` "`gamma_rgb`"', { description: 'Used by "Auto Levels", "Levels" filters.', range: true }],
	['`DCEv` "`gaussian_blur_radius`"', { description: 'Used by "Gaussian Blur" filter.', range: true }],
	['`DCEv` "`gradientFill`"', { description: [
		'Used by "Photoshop Live Effects" filter: "Gradient Overlay".',
		'',
		'This is an "&"-separated string, for example:',
		'',
		'```text',
		'0&0&1&100.000000&90.000000&100.000000&0.000000&0.000000&normal&linear&Two_Color,customStops,4096.000000$2$2,0$50$userStop$RGBColor;0.000000;0.000000;0.000000,4096$50$userStop$RGBColor;255.000000;255.000000;255.000000,100.000000$0$50,100.000000$4096$50',
		'```',
	].join('\n'), range: false }],
	['`DCEv` "`green_points`"', { description: 'Used by "Curves" filter.' }],
	['`DCEv` "`height`"', { description: 'Internal data used by Connector Line autoshape.', range: false }],
	['`DCEv` "`hls_colorize`"', { description: 'Used by "Hue/Saturation" filter.', values: new Map([['false', 'adjust existing pixel hue'], ['true', 'replace pixel hue'], ['1', 'replace pixel hue']]) }],
	['`DCEv` "`hue_amount`"', { description: 'Used by "Hue/Saturation" filter.', range: '`-180`..`180` (degrees), or `0`..`360` (degrees) if [`DCEv` "`hls_colorize`"] is `true`' }],
	['`DCEv` "`innerGlow`"', { description: [
		'Used by "Photoshop Live Effects" filter: "Inner Glow".',
		'',
		'This is an "&"-separated string, for example:',
		'',
		'```text',
		'0&0&screen&75.000000:0.000000:5.000000:0.000000:0.000000:50.000000&softMatte&RGBColor;255.000000;255.000000;189.996109&nogradient&2$$0.000000;0.000000;1$255.000000;255.000000;1&edgeGlow',
		'```',
	].join('\n'), range: false }],
	['`DCEv` "`innerShadow`"', { description: [
		'Used by "Photoshop Live Effects" filter: "Inner Shadow".',
		'',
		'This is an "&"-separated string, for example:',
		'',
		'```text',
		'0&75.000000&0&-135.000000&0.000000&5.000000&5.000000&0.000000&0&0&multiply&RGBColor;0.000000;0.000000;0.000000&2$$0.000000;0.000000;1$255.000000;255.000000;1',
		'```',
	].join('\n'), range: false }],
	['`DCEv` "`lightness_amount`"', { description: 'Used by "Hue/Saturation" filter.', range: '`-100`..`100` (percent)' }],
	['`DCEv` "`locked`"', { description: 'Internal data used by Rounded Rectangle autoshape.', range: false }],
	['`DCEv` "`maxNodes`"', { description: 'Internal data used by Polygon autoshape (duplicated in [`DCEv` "`constants`"."`maxNodes`"]).', range: false }],
	['`DCEv` "`minNodes`"', { description: 'Internal data used by Polygon autoshape (duplicated in [`DCEv` "`constants`"."`minNodes`"]).', range: false }],
	['`DCEv` "`mkbFile_WriteOnly_TemporaryEffectUiName`"', { noValueDetails: true }],
	['`DCEv` "`mode`"', { description: 'Internal data used by Connector Line autoshape.', range: false }],
	['`DCEv` "`motion_blur_angle`"', { description: 'Used by "Motion Blur" filter.', range: '`0`..`360` (degrees)' }],
	['`DCEv` "`motion_blur_distance`"', { description: 'Used by "Motion Blur" filter.', range: true }],
	['`DCEv` "`name`"', { noValueDetails: true }],
	['`DCEv` "`nodes`"', { description: 'Internal data used by Star, Polygon autoshapes.', range: true, noValueDetails: true }],
	['`DCEv` "`offset1`"', { description: 'Internal data used by Connector Line autoshape.', range: false }],
	['`DCEv` "`offset2`"', { description: 'Internal data used by Connector Line autoshape.', range: false }],
	['`DCEv` "`outerGlow`"', { description: [
		'Used by "Photoshop Live Effects" filter: "Outer Glow".',
		'',
		'This is an "&"-separated string, for example:',
		'',
		'```text',
		'0&0&screen&75.000000:0.000000:5.000000:0.000000:0.000000:50.000000&softMatte&RGBColor;255.000000;255.000000;189.996109&nogradient&2$$0.000000;0.000000;1$255.000000;255.000000;1&',
		'```',
	].join('\n'), range: false }],
	['`DCEv` "`patternFill`"', { description: [
		'Used by "Photoshop Live Effects" filter: "Pattern Overlay".',
		'',
		'This is an "&"-separated string, for example:',
		'',
		'```text',
		'0&1&100.000000&100.000000&0.000000&0.000000&normal&Bubbles&b7334da0-122f-11d4-8bb5-e27e45023b5f',
		'```',
	].join('\n'), range: false }],
	['`DCEv` "`radial_blur_amount`"', { description: 'Used by "Radial Blur" filter.', range: true }],
	['`DCEv` "`radial_blur_quality`"', { description: 'Used by "Radial Blur" filter.', range: true }],
	['`DCEv` "`radius0`"', { description: 'Internal data used by Polygon autoshape.', range: false }],
	['`DCEv` "`radius1`"', { description: 'Internal data used by Polygon autoshape.', range: false }],
	['`DCEv` "`radius`"', { description: 'Internal data used by Spiral autoshape.', range: false }],
	['`DCEv` "`red_points`"', { description: 'Used by "Curves" filter.' }],
	['`DCEv` "`rgb_points`"', { description: 'Used by "Curves" filter.' }],
	['`DCEv` "`rotation`"', { description: 'Internal data used by Polygon autoshape.', range: false }],
	['`DCEv` "`round0`"', { description: 'Internal data used by Star autoshape.', range: false }],
	['`DCEv` "`round1`"', { description: 'Internal data used by Star autoshape.', range: false }],
	['`DCEv` "`roundness`"', { description: 'Internal data used by Arrow autoshape.', range: false }],
	['`DCEv` "`satin`"', { description: [
		'Used by "Photoshop Live Effects" filter: "Satin".',
		'',
		'This is an "&"-separated string, for example:',
		'',
		'```text',
		'0&0&1&70.000000&19.000000&23.000000&15.000000&multiply&RGBColor;0.000000;0.000000;0.000000&9$$0.000000;0.000000;1$32.000000;7.000000;1$64.000000;38.000000;1$96.000000;101.000000;1$128.000000;166.000000;1$159.000000;209.000000;1$191.000000;235.000000;1$223.000000;248.000000;1$255.000000;255.000000;1',
		'```',
	].join('\n'), range: false }],
	['`DCEv` "`saturation_amount`"', { description: 'Used by "Hue/Saturation" filter.', range: true }],
	['`DCEv` "`shapeName`"', { description: 'Internal data used by autoshapes.', noValueDetails: true }],
	['`DCEv` "`sides`"', { description: 'Internal data used by Polygon autoshape.', range: false }],
	['`DCEv` "`sky_color`"', { description: 'Used by "Clouds" filter.\n\nA colour in "#rrggbb" format', range: false }],
	['`DCEv` "`solidFill`"', { description: [
		'Used by "Photoshop Live Effects" filter: "Color Overlay".',
		'',
		'This is an "&"-separated string, for example:',
		'',
		'```text',
		'0&100.000000&normal&RGBColor;255.000000;0.000000;0.000000',
		'```',
	].join('\n'), range: false }],
	['`DCEv` "`source_high_blue`"', { description: 'Used by "Auto Levels", "Levels" filters.', range: true }],
	['`DCEv` "`source_high_green`"', { description: 'Used by "Auto Levels", "Levels" filters.', range: true }],
	['`DCEv` "`source_high_red`"', { description: 'Used by "Auto Levels", "Levels" filters.', range: true }],
	['`DCEv` "`source_high_rgb`"', { description: 'Used by "Auto Levels", "Levels" filters.', range: true }],
	['`DCEv` "`source_low_blue`"', { description: 'Used by "Auto Levels", "Levels" filters.', range: true }],
	['`DCEv` "`source_low_green`"', { description: 'Used by "Auto Levels", "Levels" filters.', range: true }],
	['`DCEv` "`source_low_red`"', { description: 'Used by "Auto Levels", "Levels" filters.', range: true }],
	['`DCEv` "`source_low_rgb`"', { description: 'Used by "Auto Levels", "Levels" filters.', range: true }],
	['`DCEv` "`split`"', { description: 'Internal data used by Polygon autoshape.', range: false }],
	['`DCEv` "`stroke`"', { description: [
		'Used by "Photoshop Live Effects" filter: "Stroke".',
		'',
		'This is an "&"-separated string, for example:',
		'',
		'```text',
		'0&100.000000&3.000000&normal&RGBColor;255.000000;0.000000;0.000000&outsetFrame&solidColor&',
		'```',
	].join('\n'), range: false }],
	['`DCEv` "`t1`"', { description: 'Internal data used by Arrow Tool autoshape.', range: false }],
	['`DCEv` "`t2`"', { description: 'Internal data used by Arrow Tool autoshape.', range: false }],
	['`DCEv` "`thickness`"', { description: 'Internal data used by Arrow Tool autoshape.', range: false }],
	['`DCEv` "`toolTips`"', { description: 'Internal data used by autoshapes.' }],
	['`DCEv` "`toolTips`"."`angle`"', { description: 'Internal data used by autoshapes.', range: false }],
	['`DCEv` "`toolTips`"."`drag`"', { description: 'Internal data used by autoshapes.', range: false }],
	['`DCEv` "`toolTips`"."`head`"', { description: 'Internal data used by autoshapes.', range: false }],
	['`DCEv` "`toolTips`"."`inch`"', { description: 'Internal data used by autoshapes.', range: false }],
	['`DCEv` "`toolTips`"."`length`"', { description: 'Internal data used by autoshapes.', range: false }],
	['`DCEv` "`toolTips`"."`of`"', { description: 'Internal data used by autoshapes.', range: false }],
	['`DCEv` "`toolTips`"."`px`"', { description: 'Internal data used by autoshapes.', range: false }],
	['`DCEv` "`toolTips`"."`resize`"', { description: 'Internal data used by autoshapes.', range: false }],
	['`DCEv` "`tooltips`"', { description: 'Internal data used by autoshapes.' }],
	['`DCEv` "`tooltips`"."`altopt`"', { description: 'Internal data used by autoshapes.', range: false }],
	['`DCEv` "`tooltips`"."`inner`"', { description: 'Internal data used by autoshapes.', range: false }],
	['`DCEv` "`tooltips`"."`openclose`"', { description: 'Internal data used by autoshapes.', range: false }],
	['`DCEv` "`tooltips`"."`points`"', { description: 'Internal data used by autoshapes.', range: false }],
	['`DCEv` "`tooltips`"."`radius0`"', { description: 'Internal data used by autoshapes.', range: false }],
	['`DCEv` "`tooltips`"."`radius1`"', { description: 'Internal data used by autoshapes.', range: false }],
	['`DCEv` "`tooltips`"."`radius`"', { description: 'Internal data used by autoshapes.', range: false }],
	['`DCEv` "`tooltips`"."`reset`"', { description: 'Internal data used by autoshapes.', range: false }],
	['`DCEv` "`tooltips`"."`roundness1`"', { description: 'Internal data used by autoshapes.', range: false }],
	['`DCEv` "`tooltips`"."`roundness2`"', { description: 'Internal data used by autoshapes.', range: false }],
	['`DCEv` "`tooltips`"."`scale`"', { description: 'Internal data used by autoshapes.', range: false }],
	['`DCEv` "`tooltips`"."`sections`"', { description: 'Internal data used by autoshapes.', range: false }],
	['`DCEv` "`tooltips`"."`sides`"', { description: 'Internal data used by autoshapes.', range: false }],
	['`DCEv` "`tooltips`"."`spirals`"', { description: 'Internal data used by autoshapes.', range: false }],
	['`DCEv` "`unsharp_mask_amount`"', { description: 'Used by "Unsharp Mask" filter.', range: true }],
	['`DCEv` "`unsharp_mask_radius`"', { description: 'Used by "Unsharp Mask" filter.', range: true }],
	['`DCEv` "`unsharp_mask_threshold`"', { description: 'Used by "Unsharp Mask" filter.', range: true }],
	['`DCEv` "`usecolor`"', { description: 'Used by "Solid Shadow" filter.', values: new Map([['false', 'shadow colour is extension of edge colour'], ['true', 'shadow colour is set by [`DCEv` "`color`"]']]) }],
	['`DCEv` "`width`"', { description: 'Internal data used by Connector Line autoshape.', range: false }],
	['`DCEv` "`x1`"', { description: 'Internal data used by Measure Tool autoshape.', range: false }],
	['`DCEv` "`x2`"', { description: 'Internal data used by Measure Tool autoshape.', range: false }],
	['`DCEv` "`y1`"', { description: 'Internal data used by Measure Tool autoshape.', range: false }],
	['`DCEv` "`y2`"', { description: 'Internal data used by Measure Tool autoshape.', range: false }],
	['`DCEv` "`zoom_blur_amount`"', { description: 'Used by "Zoom Blur" filter.', range: true }],
	['`DCEv` "`zoom_blur_quality`"', { description: 'Used by "Zoom Blur" filter.', range: true }],
	['`DCKs`', { name: '**D**i**c**tionary Entry **K**ey', description: 'The key name for a key-value pair.', range: false }],
	['`DCVs`', { name: '**D**i**c**tionary Entry String **V**alue', description: 'A string value for a key-value pair.', range: false }],
	['`DF1i`', { name: '**D**ash O**f**f **1**', range: true }],
	['`DF2i`', { name: '**D**ash O**f**f **2**', range: true }],
	['`DF3i`', { name: '**D**ash O**f**f **3**', range: true }],
	['`DISb`', { name: '**Dis**play', values: new Map([[true, 'the node is open in the layer list'], [false, 'the node is collapsed in the layer list']]) }],
	['`DO1i`', { name: '**D**ash **O**n **1**', range: true }],
	['`DO2i`', { name: '**D**ash **O**n **2**', range: true }],
	['`DO3i`', { name: '**D**ash **O**n **3**', range: true }],
	['`DSUb`', { name: 'HTML **D**rop Un-**S**liced Areas', values: new Map([[false, 'include areas without slice objects'], [true, 'omit areas without slice objects']]) }],
	['`DTAv`', { name: '**D**a**ta**', description: 'Stores arbitrary, possibly nested, data for JavaScript scripts, as set on `smartShape.elem.customData`.' }],
	['`DURi`', { name: '**Dur**ation', range: true }],
	['`DVLb`', {}],
	['`ECSi`', { name: 'HTML **E**xternal **CS**S', values: new Map([[0, 'use inline CSS'], [1, 'use external file for CSS']]) }],
	['`EFBs`', { name: 'Last **E**xport **F**ilename', description: 'Last filename used for export (excluding path and extension)', range: false }],
	['`EFDv`', { name: '**Ef**fect **D**efinitions', description: 'Preset effects / defaults offered in the UI' }],
	['`EFLv`', { name: '**Ef**fect **L**ist' }],
	['`EFXs`', { name: '**E**xport **F**ile Filter.', noValueDetails: true }],
	['`ELMv`', { name: '**El**e**m**ents' }],
	['`ENCi`', { name: 'HTML **Enc**oding', values: new Map([[0, 'ASCII'], [1, 'UTF-8']]) }],
	['`EOFb`', { name: '**E**ven-**O**dd **F**ill Rule', values: new Map([[true, 'even-odd fill rule'], [false, 'nonzero fill rule']]) }],
	['`EPSv`', { name: '**E**ffect **P**ropertie**s**', description: 'Defines an effect (such as a drop-shadow). See [`DCEv` "`EffectMoaID`"] for the type of effect applied.' }],
	['`EXPv`', { name: '**Exp**ort Options' }],
	['`FABi`', { description: 'A **signed** 32-bit number, relating to Bottom.' }],
	['`FALi`', { description: 'A **signed** 32-bit number, relating to Left.' }],
	['`FARi`', { description: 'A **signed** 32-bit number, relating to Right.' }],
	['`FATi`', { description: 'A **signed** 32-bit number, relating to Top.' }],
	['`FCLi`', { name: '**F**ill **C**o**l**our', range: '`0x00000000`..`0xffffffff`', description: 'ABGR format colour.' }],
	['`EXPv`.`FCLi`', { name: 'Matte **C**o**l**our', range: '`0x00000000`..`0xffffffff`', description: 'ABGR format colour.' }],
	['`BEHv`.`FCLi`', { name: '**M**enu **I**tem **T**ext Colour', description: 'ABGR (?) format colour for the text of highlighted menu items.', range: '`0x00000000`..`0xffffffff`' }],
	['`FD1i`', { name: '**F**ill **D**ither Colour **1**', range: '`0x00000000`..`0xffffffff`' }],
	['`FD2i`', { name: '**F**ill **D**ither Colour **2**', range: '`0x00000000`..`0xffffffff`' }],
	['`FD3i`', { name: '**F**ill **D**ither Colour **3**', range: '`0x00000000`..`0xffffffff`' }],
	['`FD4i`', { name: '**F**ill **D**ither Colour **4**', range: '`0x00000000`..`0xffffffff`' }],
	['`FDTb`', { name: '**F**ill **D**ither **T**ransparent', range: false }],
	['`FEFi`', { name: '**Fe**ather **F**ill Amount', range: true }],
	['`FPLv`.`FETi`', { description: 'Seems related to hard edge / non-anti-aliased fills' }],
	['`BEHv`.`FETi`', {}],
	['`FG0v`', { name: '**F**ill **G**radient **0** (RGB)' }],
	['`FG1v`', { name: '**F**ill **G**radient **1** (Alpha)' }],
	['`FGCi`', { name: '**F**ill **G**radient Control Point **C**olour', range: '`0x00000000`..`0xffffffff`' }],
	['`FGIv`', { name: '**F**ill **G**radient Control Point' }],
	['`FGLv`', { name: '**F**ill **G**radient' }],
	['`FGPf`', { name: '**F**ill **G**radient Control Point **P**osition', range: true }],
	['`FGVv`', { name: '**F**ill **G**radient **V**ertices' }],
	['`FGYv`', { name: '**F**ill **G**radient RGB + Alpha' }],
	['`FILs`', { name: '**L**abel', range: false }],
	['`FLDv`', { name: '**F**i**l**l Type **D**efinitions', description: 'Fill styles which are offered in the UI (e.g. linear gradient, radial gradient).' }],
	['`FLPi`', { name: '**F**rame **L**oo**p**', description: 'Number of times to repeat the animation. `0` = infinite, `4294967295` (`-1`) = no loop', range: false }],
	['`FMTi`', { name: '**F**or**m**a**t**', values: new Map([[0, 'gif'], [1, 'jpeg'], [2, 'png'], [3, 'bitmap / pict / tiff / wbmp (disambiguated by [`MCTi`])'], [4, 'animated gif']]) }],
	['`FNCi`', { name: '**F**ill Gradient **N**umber of **C**ontrol Points', range: false }],
	['`FNDi`', { name: '**F**rame **D**uration', range: '`0`..`100` (hundredths of a second)' }],
	['`FNLv`', { name: '**F**rame Configuration **L**ist' }],
	['`FNMv`', { name: '**F**ra**m**e Configuration' }],
	['`FNPi`', {}],
	['`FOAb`', {}],
	['`FONs`', { name: '**Fon**t Family', noValueDetails: true }],
	['`FOTb`', { name: '**F**ill **O**n **T**op', values: new Map([[true, 'fill over stroke'], [false, 'stroke over fill']]) }],
	['`FPLv`', { name: '**F**ill **P**attern Properties' }],
	['`FPTv`', { name: '**F**ill **P**attern **T**ile' }],
	['`FRCi`', { name: '**Fr**ame **C**ount', description: 'The number of animation frames. It is not clear why this node is duplicated.', range: false }],
	['`FRDb`', { name: '**F**ill Ha**rd** Edge', values: new Map([[true, 'hard (non-anti-aliased) edge'], [false, 'anti-aliased edge']]) }],
	['`FRRi`', {}],
	['`FSHi`', { name: '**F**ill **Sh**ape', description: 'This is for backwards compatibility; [`FSXi`] is preferred if available', values: new Map([
		[0, 'solid'],
		[2, 'linear'],
		[3, 'radial or contour'],
		[4, 'conical'],
		[5, 'satin'],
		[7, 'pinch'],
		[8, 'folds'],
		[9, 'elliptical'],
		[10, 'rectangular'],
		[12, 'bars'],
		[13, 'ripple'],
		[14, 'waves'],
		[15, 'pattern'],
		[16, 'web dither'],
	]) }],
	['`FSMi`', { name: '**F**ill **S**tamping **M**ode', values: new Map([[1, 'transparent ("blend")'], [2, 'white ("blend opaque")']]) }],
	['`FSXi`', { name: '**F**ill **S**hape E**x**tended', values: new Map([
		[0, 'solid'],
		[2, 'linear'],
		[3, 'radial'],
		[4, 'conical'],
		[5, 'satin'],
		[7, 'pinch'],
		[8, 'folds'],
		[9, 'elliptical'],
		[10, 'rectangular'],
		[12, 'bars'],
		[13, 'ripple'],
		[14, 'waves'],
		[15, 'pattern'],
		[16, 'web dither'],
		[17, 'contour grad'],
	]) }],
	['`FTBi`', { name: '**F**ill **T**exture **B**lending', range: '`0`..`1000` (per mille)' }],
	['`GCLi`', { name: '**G**rid **C**o**l**our', range: '`0x00000000`..`0xffffffff`', description: 'ABGR format colour.' }],
	['`GDCf`', { name: '**G**ui**d**e **C**oordinate', range: false }],
	['`GDHv`', { name: '**G**ui**d**es **H**orizontal' }],
	['`GDKi`', { name: '**G**ui**d**es Colour', range: '`0x00000000`..`0xffffffff`', description: 'ABGR format colour.' }],
	['`GDLb`', { name: '**G**ui**d**es **L**ocked', range: false }],
	['`GDSv`', { name: '**G**ui**d**e**s**' }],
	['`GDTv`', { name: 'Nested **D**ic**t**ionary' }],
	['`GDVv`', { name: '**G**ui**d**es **V**ertical' }],
	['`GFIb`', { name: '**I**nterlaced', values: new Map([[true, 'exported image uses interlacing'], [false, 'exported image loads from top to bottom']]) }],
	['`GLDv`', { name: '**G**radient **L**ist **D**efinitions', description: 'Gradients which are offered in the UI as "presets".' }],
	['`GLTi`', { name: '**G**IF **L**oss', range: true }],
	['`GOXf`', { name: '**G**rid **O**ffset **X**', range: false }],
	['`GOYf`', { name: '**G**rid **O**ffset **Y**', range: false }],
	['`GPLv`', { name: '**G**rab **P**oint **L**ist' }],
	['`GPTv`', { name: '**G**rab **P**oin**t**', description: 'A grabble point of a colour transform curve.' }],
	['`GRDv`', { name: '**Gr**i**d**' }],
	['`GRPv`', { name: '**Gr**ou**p**' }],
	['`GRTi`', { name: '**Gr**oup **T**ype', values: new Map([[0, 'regular'], [1, 'grayscale mask (first element in parent node\'s [`ELMv`] = mask, second = masked)'], [2, 'shape mask (first element in parent node\'s [`ELMv`] = mask, second = masked)']]) }],
	['`GSLb`', {}],
	['`GSXf`', { name: '**G**rid **S**ize **X**', range: false }],
	['`GSYf`', { name: '**G**rid **S**ize **Y**', range: false }],
	['`HICi`', { name: '**Hi**ghlight **C**olour', description: 'An ABGR colour for the popup menu border highlight.' }],
	['`HIMb`', {}],
	['`HITf`', { name: '**H**e**i**gh**t**', description: 'The height of the document (pixels).', range: false }],
	['`HPXi`', { name: '**H**eight **P**i**x**els', description: 'The height of a raster image.', range: false }],
	['`HSCf`', { name: '**H**orizontal **Sc**ale', range: true }],
	['`HTMb`', { name: 'Export **HTM**L', description: 'When exporting a whole page, this controls whether it will generate a HTML document.', range: false }],
	['`HTMi`', { name: 'Export **HTM**L Layout', values: new Map([[0, 'HTML and images together'], [1, 'Put images in a subfolder'], [3, 'Copy HTML to clipboard']]) }],
	['`HTTs`', { name: '**HT**ML S**t**yle', noValueDetails: true }],
	['`IDSb`', {}],
	['`ILLb`', { description: 'Observed in all Fireworks CS4 files, not seen in Fireworks 8 files. Always seems to be `false`.', values: new Map([[false, 'unknown']]) }],
	['`IMDs`', { name: '**Im**age **D**irectory', description: 'Directory where image was last exported, as a URI beginning with "file://"', range: false }],
	['`IMGv`', { name: '**Im**a**g**e', description: 'A raster image, composed of one or more [`mkBT`] tiles. This is typically a "cached" render of vector data (e.g. rendered text)' }],
	['`IMPb`', { name: '**I**s **M**aster **P**age', description: 'One page can be marked as the master page, which is then referenced by [`MPLv`] nodes in each page (using [`PIDs`])', range: false }],
	['`INMs`', { name: '**I**nternal **N**a**m**e', noValueDetails: true }],
	['`IODb`', {}],
	['`ISCb`', { name: '**Is** **C**losed', values: new Map([[true, 'path is closed (last point links to first)'], [false, 'path is open']]) }],
	['`ISPb`', { name: '**Is** **P**rimary', values: new Map([
		[true, 'this is the primary definition of the element (an [`LSEv`])'],
		[false, 'this is a reference to an element defined elsewhere, based on the [`UIDs`] value (an [`LSAv`])'],
	]) }],
	['`ISSv`', { name: '**S**mart **S**hape' }],
	['`ITLb`', { name: '**It**a**l**ic', values: new Map([[true, 'begin italic'], [false, 'end italic']]) }],
	['`JPOi`', { name: '**JP**EG C**o**lour', values: new Map([[0, 'sharp colour edges'], [1, 'smooth colour edges']]) }],
	['`JPPb`', { name: '**JP**EG **P**rogressive', values: new Map([[true, 'exported JPEG is arranged to load in low quality first then gain resolution'], [false, 'exported JPEG loads in full resolution from top to bottom']]) }],
	['`JPQi`', { name: '**JP**EG **Q**uality', range: '`0`..`100` (percent)' }],
	['`JPSi`', { name: '**JP**EG **S**moothing', range: '`0`..`8`' }],
	['`JSBb`', {}],
	['`JSEb`', {}],
	['`JSQi`', {}],
	['`JSSs`', { name: '**J**ava**S**cript **S**ubstring', description: 'A fragment of a JavaScript script.', range: false }],
	['`JSTb`', {}],
	['`JSTi`', { name: '**J**u**st**ification', values: new Map([[0, 'left'], [1, 'centre'], [2, 'right'], [3, 'fully justified']]) }],
	['`JSVv`', { name: '**J**ava**S**cript Script', description: 'A JavaScript script, potentially split into multiple [`JSSs`] pieces which must be concatenated together (this is to avoid the 65535-byte string length limit of the data format). Used for calculating changes to smart shapes.' }],
	['`KRNf`', {}],
	['`LAYv`', { name: '**Lay**er', description: 'An individual top-level layer. Nested layers use [`LSLv`].' }],
	['`LCKb`', { name: '**L**o**ck**', values: new Map([[true, 'the parent node is locked and cannot be manipulated in the editor'], [false, 'the parent node is not locked and can be manipulated']]) }],
	['`LDMi`', { name: '**L**ine Height Unit', values: new Map([[0, 'em'], [1, 'pixels']]) }],
	['`LEDf`', { name: '**L**ine Height', description: 'Line height, in units defined by [`LDMi`]', range: true }],
	['`LFAf`', { name: '**L**e**f**t **A**nchor', description: 'Typically this is the same as [`LFTf`]. See [`PINf`] for an explanation of when this property will differ.' }],
	['`LFTf`', { name: '**L**e**ft**', description: 'Distance (pixels) from left of container to left of entity.', range: false }],
	['`LLLi`', { name: '**L**ayer Nesting **L**evel', description: 'Appears to be the indentation level for the layer, counting from `0` for root-level layers.', range: false }],
	['`LNKb`', { name: '**L**i**nk**ed', description: 'For mask groups, this controls whether the mask moves when the content is moved. Note that this node is never present with a value of `true`; `true` is implied by its absence.', values: new Map([[false, 'Content moves independently of mask']]) }],
	['`LNMs`', { name: '**L**ayer **N**a**m**e', range: false }],
	['`LRBi`', { name: 'Export A**r**ea **B**ottom', description: 'Y coordinate of bottom of export area (or not present if entire image is to be exported).', range: false }],
	['`LRLi`', { name: 'Export A**r**ea **L**eft', description: 'X coordinate of left of export area (or not present if entire image is to be exported).', range: false }],
	['`LRRi`', { name: 'Export A**r**ea **R**ight', description: 'X coordinate of right of export area (or not present if entire image is to be exported).', range: false }],
	['`LRTi`', { name: 'Export A**r**ea **T**op', description: 'Y coordinate of top of export area (or not present if entire image is to be exported).', range: false }],
	['`LSAv`', { name: '**L**ayer **S**ource Link', description: 'Links to an [`LSEv`] from the master page.' }],
	['`LSDb`', { name: 'HTML Multiple Nav Bars', description: '"Export multiple nav bar HTML files (for use without frame sets)".', range: false }],
	['`LSEv`', { name: '**L**ayer **S**hared Definition', description: 'Same as [`LAYv`] but defines a layer for future reference by [`LSAv`] rather than to display.' }],
	['`LSLv`', { name: '**L**ayer **S**ub-**L**ayer', description: 'A layer nested inside another layer. Shares the same structure as [`LAYv`].' }],
	['`LSMv`', { name: '**L**ayer **S**hared Definitions', description: 'Contains definitions of layers which are shared between pages and can be referenced by [`LSAv`] nodes. Appears to always be empty in [`PDCv`] nodes.' }],
	['`LSSi`', { name: 'HTML **S**lice **S**pacing', values: new Map([[0, 'Single Table - No Spacers'], [1, '1-Pixel Transparent Spacer'], [3, 'Nested Tables - No Spacers']]) }],
	['`LSUb`', {}],
	['`LUTs`', { name: '**L**ast **U**pdate **T**ime', description: 'Last update time for this symbol, in `d/M/yy HH:mm` format.', range: false }],
	['`LXDs`', { name: '**L**ast E**x**port **D**irectory', description: 'The last directory where the file was exported. The copy in [`MKBv`] / [`PDCv`] is presumably for backwards compatibility.', range: false }],
	['`LXFs`', { name: '**L**ast E**x**port **F**ilename', range: false }],
	['`LYLv`', { name: '**L**a**y**er **L**ist', description: 'An ordered list of layers.' }],
	['`M00f`', { name: '**M**atrix Element **0**, **0**', range: false }],
	['`M01f`', { name: '**M**atrix Element **0**, **1**', range: false }],
	['`M02f`', { name: '**M**atrix Element **0**, **2**', range: false }],
	['`M10f`', { name: '**M**atrix Element **1**, **0**', range: false }],
	['`M11f`', { name: '**M**atrix Element **1**, **1**', range: false }],
	['`M12f`', { name: '**M**atrix Element **1**, **2**', range: false }],
	['`M20f`', { name: '**M**atrix Element **2**, **0**', range: false }],
	['`M21f`', { name: '**M**atrix Element **2**, **1**', range: false }],
	['`M22f`', { name: '**M**atrix Element **2**, **2**', range: false }],
	['`MCCi`', { description: 'Appears to represent a 4-character ASCII string.', values: new Map([[1296777817, '"MKBY"']]) }],
	['`MCLb`', { name: 'Fra**m**e **C**hanging **L**ayer', values: new Map([[false, 'layer is shared across all frames; only the first [`CELv`] has content; the rest are stubs'], [true, 'layer has unique content for each frame']]) }],
	['`MCTi`', { description: 'Image format disambiguation if [`FMTi`] is `3`. Represents a 4-character ASCII string.', values: new Map([
		[1112363040, '"BMP "'],
		[1346978644, '"PICT"'],
		[1414088262, '"TIFF"'],
		[1463962960, '"WBMP"'],
	]) }],
	['`MIDi`', { name: 'Text **C**olour Hover', description: 'A BGRA (?) colour for the text of highlighted menu items.', range: '`0x00000000`..`0xffffffff`' }],
	['`MIHi`', { name: '**M**enu **I**tem **H**eight', range: false }],
	['`MITi`', { name: '**M**enu **I**ndent **T**ext', range: false }],
	['`MIVb`', { name: '**M**enu **I**tems **V**ertical', values: new Map([[false, 'menu is arranged horizontally'], [true, 'menu is arranged vertically']]) }],
	['`MIWi`', { name: '**M**enu **I**tem **W**idth', range: false }],
	['`MKBv`', { name: 'Document', description: 'Defines any layer content which is shared between pages (in [`LSMv`] as [`LSEv`] nodes with a [`UIDs`] for individual pages to reference), and includes a slightly reduced copy of page 1 (first [`PDCv`]), including a copy of the master page\'s layers (if set). This is possibly for backwards compatibility. The `mkBS` chunk (Fireworks attribution) _only_ defines [`MKBv`] and does not include any [`PDCv`] chunks; this may be a glimpse of an old file structure.' }],
	['`MNAb`', { name: '**M**ask **N**ot **A**ppear', description: 'For mask groups, this controls whether the mask image itself is visible (toggled in Fireworks via "Show fill and stroke"). Note that this node is never present with a value of `false`; `false` is implied by its absence.', values: new Map([[true, 'Mask is hidden.']]) }],
	['`MNDs`', { name: '**D**efault ALT Tag', range: false }],
	['`MNFv`', {}],
	['`MOXf`', {}],
	['`MOYf`', {}],
	['`MPLv`', { name: '**M**aster **P**age **L**ink', description: 'References all layers from another [`PDCv`] (the "Master Page"), by [`PIDs`]. The referenced layers are atomic, but the whole structure can be displayed / hidden for this specific page as part of the reference.' }],
	['`MRMv`', { description: 'Grayscale mask definition ?' }],
	['`MSKv`', { name: '**M**a**sk**', description: 'A raster mask, composed of one or more [`mkBT`] tiles.' }],
	['`MSLb`', { name: '**S**pecial **L**ayer', values: new Map([[false, 'regular layer'], [true, 'special layer (currently: "Web Layer") - presumably blocks actions like deletion']]) }],
	['`MSLv`', { name: '**S**ymbol Definition **L**ist' }],
	['`MSNi`', { name: '**S**ymbol Unique **N**umber', description: 'A 32-bit number which uniquely defines a symbol in the document. Used to link [`ALSv`] instances to [`MSTv`] definitions.' }],
	['`MSTv`', { name: '**S**ymbol Definition', description: 'A node containing many of the same elements as a page ([`PDCv`]), defining a symbol which can be referenced multiple times in the document by [`ALSv`] nodes with [`MSNi`] IDs.' }],
	['`MSYi`', { name: '**S**ymbol T**y**pe', description: 'Graphic symbols omit this node rather than setting it to 0.', values: new Map([[1, 'button'], [2, 'animation']]) }],
	['`MTXv`', { name: '**M**a**t**ri**x**', description: 'A 3&times;3 matrix.' }],
	['`NDIi`', { name: '**N**umber of **D**ashes', description: 'Defines which of [`DO1i`] / [`DF1i`] .. [`DO3i`] / [`DF3i`] are used', range: '`0`..`3`' }],
	['`NGCf`', { name: '**N**ine Slice **G**uide **C**ontrol', description: 'A set of 4 ordered control points for the 9-slice guide: top, bottom, left, right', range: false }],
	['`NGKi`', { name: '**N**ine Slice **G**uide Colour', description: 'An ARGB (or BGRA?) colour for the 9-slice guide-lines.', range: '`0x00000000`..`0xffffffff`' }],
	['`NGLb`', { name: '**N**ine Slice **G**uide **L**ocked', range: false }],
	['`NGMv`', { name: '**N**ine Slice **G**uide Shape Bounds', description: 'Bounds of the symbol\'s content, relative to the symbol origin.' }],
	['`NGSv`', { name: '**N**ine **S**lice Guide' }],
	['`NGVv`', { name: '**N**ine Slice **G**uide Limits', description: 'Bounds of the space available for the 9-slice guide, relative to the symbol origin (defines a space a few pixels larger than the canvas).' }],
	['`NM4i`', { name: 'HTML Slice Export **N**a**m**e Part', values: new Map([
		[0, 'None'],
		[1, 'Row Column (r3_c2, r4_c7...)'],
		[2, 'Slice # (A,B,C...)'],
		[3, 'Slice # (a,b,c...)'],
		[4, 'Slice # (1, 2, 3...)'],
		[5, 'Slice # (01, 02, 03...)'],
		[6, 'doc.name (filename without path or extension)'],
		[7, '"slice"'],
		[15, '"_"'],
		[16, '"."'],
		[17, '" "'],
		[18, '"-"'],
	]) }],
	['`NM4v`', { name: 'HTML Slice Export **N**a**m**es', description: '6 name parts which are concatenated together to form a filename when exporting HTML slices.' }],
	['`NMFi`', { name: 'HTML Slice Export **N**a**m**e **F**rame Part', values: new Map([
		[0, 'None'],
		[1, 'State # (f2, f3, f4...)'],
		[2, 'State # (2, 3, 4...)'],
		[3, 'Rollover (over, down, overdown)'],
		[4, 'Abbreviated (o, d, od)'],
		[5, '"_"'],
		[6, '"."'],
		[7, '" "'],
		[8, '"-"'],
	]) }],
	['`NMFv`', { name: 'HTML Slice Export **N**a**m**es **F**rame', description: '2 name parts which are concatenated together (and combined with [`NM4v`]) to form a filename when exporting HTML slices with states.' }],
	['`NSDf`', { name: '**S**egment **D**istance', description: 'Cached length (in pixels) of the upcoming curve segment. Omitted if the segment has a length of 0 or is the last in the path (and the path is not closed).', range: false }],
	['`NYSb`', {}],
	['`OBNs`', { name: '**Ob**ject **N**ame', range: false }],
	['`ONCb`', { name: '**On** **C**ontrol Point', values: new Map([[true, 'point is exactly on a control point'], [false, 'point is an interpolation between control points']]) }],
	['`OPAi`', { name: '**Opa**city', range: '`0` (transparent) .. `1000` (opaque)' }],
	['`OPQb`', {}],
	['`ORIi`', { name: '**Ori**entation', values: new Map([[0, 'left-to-right'], [1, 'top-to-bottom'], [3, 'top-to-bottom (TODO: unknown distinction from `1`)']]) }],
	['`OSAi`', { name: '**O**nion **S**kinning **A**fter Frames', description: 'Number of frames after the current frame to display for onion skinning.', range: '`0`..inf' }],
	['`OSBi`', { name: '**O**nion **S**kinning **B**efore Frames', description: 'Number of frames before the current frame to display for onion skinning.', range: '`0`..inf' }],
	['`OVHb`', { name: '**Ov**erride **H**eight', values: new Map([[false, 'cell height is calculated automatically'], [true, 'cell height is set manually']]) }],
	['`OVWb`', { name: '**Ov**erride **W**idth', values: new Map([[false, 'cell width is calculated automatically'], [true, 'cell width is set manually']]) }],
	['`PALv`', { name: '**Pal**ette', description: 'Contains multiple colours, each beginning with [`FCLi`] and followed by zero or more attributes' }],
	['`PATv`', { name: '**Pat**tern' }],
	['`PBLv`', { name: '**P**ath **B**ezier **L**ist' }],
	['`PBPv`', { name: '**P**ath **B**ezier **P**oints' }],
	['`PBTv`', { name: '**P**ath **B**ezier Poin**t**' }],
	['`PCFb`', {}],
	['`PCLv`', { name: '**P**ath **C**ontour **L**ist', description: 'List of interpolated paths. The source of truth for this is a [`PBLv`].' }],
	['`PDCv`', { name: '**P**age', description: 'An individual page. Contains frames ("states") and layers. Layers shared to all pages reference a source defined in [`MKBv`].' }],
	['`PEXf`', { name: 'Fill **P**oint 2 (**E**) **X**', range: false }],
	['`PEYf`', { name: 'Fill **P**oint 2 (**E**) **Y**', range: false }],
	['`PFXf`', { name: 'Fill **P**oint 3 (**F**) **X**', range: false }],
	['`PFYf`', { name: 'Fill **P**oint 3 (**F**) **Y**', range: false }],
	['`PGNs`', { name: '**P**a**g**e **N**ame', range: false }],
	['`PIDs`', { name: '**P**age **ID**', description: 'A UUID for the page.', range: false }],
	['`PILb`', { name: '**P**age **I**s **L**inked', description: 'Marks page as "linked" to the "Master Page". Linked pages are automatically updated with new properties set on the master page (e.g. background colour).', range: false }],
	['`PINf`', { name: '**P**aragraph **In**dent', description: 'Amount to indent the first line of the paragraph by. If the text is not multiline (i.e. [`ATEb`] is `true`), the [`LFTf`] value is modified and [`LFAf`] stores the original left coordinate. If the text _is_ multiline (i.e. [`ATEb`] is `false`), the [`LFTf`] and [`LFAf`] values remain equal and the indent is applied inside the text area.', range: '`0`..inf (pixels)' }],
	['`PLDi`', { name: '**P**a**l**ette **D**ither Level', range: '`0` (none) .. `100` (full)' }],
	['`PLLv`', { name: 'Brush Definitions', description: 'Preset brushes offered in the UI' }],
	['`PLNi`', { name: '**P**a**l**ette **N**umber of entries', range: false }],
	['`PLOb`', { name: '**P**a**l**ette Pruning', values: new Map([[true, 'unused colours are removed'], [false, 'unused colours remain in palette']]) }],
	['`PLRi`', { name: '**P**a**l**ette **R**emaining Colours', description: 'Number of colours actually used in palette.', range: true }],
	['`PLTi`', { name: '**P**a**l**e**t**te **T**ype', values: new Map([
		[0, 'none'],
		[1, 'adaptive'],
		[2, 'uniform'],
		[3, 'black & white'],
		[4, 'macintosh'],
		[5, 'windows'],
		[6, 'exact'],
		[7, 'web 216'],
	]) }],
	['`PPCi`', { name: '**P**ath **P**oint **C**ount', description: 'Equal to the number of [`PBTv`] nodes contained in the parent node', range: false }],
	['`PPLv`', { name: '**P**ath **P**oint **L**ist', description: 'List of points defining an interpolated path. The source of truth for this path will be a [`PBPv`].' }],
	['`PPTv`', { name: '**P**ath **P**oin**t**' }],
	['`PRIv`', { name: '**Pri**mitive', description: 'The source shape and transformation which created the current path. Allows modifying properties such as corner radius.' }],
	['`PRSf`', { name: '**Pr**e**s**sure', range: '`0`..`1`' }],
	['`PSAf`', { name: '**P**aragraph **S**pace **A**fter', description: 'Paragraph bottom margin (pixels)', range: false }],
	['`PSBf`', { name: '**P**aragraph **S**pace **B**efore', description: 'Paragraph top margin (pixels)', range: false }],
	['`PSXf`', { name: 'Fill **P**oint 1 (**S**) **X**', range: false }],
	['`PSYf`', { name: 'Fill **P**oint 1 (**S**) **Y**', range: false }],
	['`PTHv`', { name: '**P**a**th**' }],
	['`PTNi`', { name: '**P**alette **T**ra**n**sparency Type', values: new Map([[0, 'none'], [1, 'index'], [2, 'alpha'], [3, 'alpha (TODO: what is distinction from `2`?)']]) }],
	['`PTSf`', { name: 'Font **P**oin**t** **S**ize', range: false }],
	['`PTTi`', { name: '**P**a**t**h **T**emplated', values: new Map([[0, 'Path is not defined by a template (e.g. freehand or modified)'], [1, 'Path is defined by a template (e.g. ellipse, rectangle). If the shape is a rounded rectangle, it is defined in [`PRIv`].']]) }],
	['`RCTv`', { name: '**R**e**ct**angle' }],
	['`RDMb`', { name: 'Border **R**a**d**ius **M**aintain', description: '[`RDSf`] is always measured as a percentage (0-100), but if this is `true`, it will be recalculated when the shape changes size to maintain an absolute radius size.', values: new Map([[true, '[`RDSf`] is recalculated when the shape is resized to maintain a constant absolute radius'], [false, '[`RDSf`] remains constant; radius is proportional to shape size']]) }],
	['`RDOb`', {}],
	['`RDSf`', { name: 'Border **R**a**d**iu**s**', range: '`0`..`100` (percent)', description: 'This is always measured as a percentage (0-100), but if [`RDMb`] is set on the parent, it will be recalculated when the shape changes size to maintain an absolute radius size.' }],
	['`RELb`', {}],
	['`RESf`', { name: '**Res**olution', description: 'The resolution of the image. Units are specified in [`RSUi`].', range: false }],
	['`RIAf`', { description: '`0` if [`ATEb`] is `true` (i.e. if the text box auto-resizes to its content). Otherwise this is a positive integer of unknown meaning (TODO).', range: true }],
	['`RITf`', { name: '**Ri**gh**t**', description: 'Distance (pixels) from left of container to right of entity.', range: false }],
	['`RKNf`', { name: '**K**er**n**ing', range: true }],
	['`RNDi`', { name: '**R**a**nd**om Seed' }],
	['`RQNi`', {}],
	['`RSUi`', { name: '**R**e**s**olution **U**nit', description: 'The units for [`RESf`]', values: new Map([[0, 'pixels per inch'], [1, 'pixels per centimeter']]) }],
	['`SHAi`', { name: '**S**ensitivity to **H**orizontal on **A**ngle', range: '`0`..`1000` (per mille)' }],
	['`SHBi`', { name: '**S**ensitivity to **H**orizontal on **B**lackness', range: '`0`..`1000` (per mille)' }],
	['`SHHi`', { name: '**S**ensitivity to **H**orizontal on **H**ue', range: '`0`..`1000` (per mille)' }],
	['`SHLi`', { name: '**S**ensitivity to **H**orizontal on **L**ightness', range: '`0`..`1000` (per mille)' }],
	['`SHOi`', { name: '**S**ensitivity to **H**orizontal on **O**pacity', range: '`0`..`1000` (per mille)' }],
	['`SHRi`', { name: '**S**ensitivity to **H**orizontal on Scatte**r**', range: '`0`..`1000` (per mille)' }],
	['`SHSi`', { name: '**S**ensitivity to **H**orizontal on **S**aturation', range: '`0`..`1000` (per mille)' }],
	['`SHZi`', { name: '**S**ensitivity to **H**orizontal on Si**z**e', range: '`0`..`1000` (per mille)' }],
	['`SPAi`', { name: '**S**ensitivity to **P**ressure on **A**ngle', range: '`0`..`1000` (per mille)' }],
	['`SPBi`', { name: '**S**ensitivity to **P**ressure on **B**lackness', range: '`0`..`1000` (per mille)' }],
	['`SPHi`', { name: '**S**ensitivity to **P**ressure on **H**ue', range: '`0`..`1000` (per mille)' }],
	['`SPLi`', { name: '**S**ensitivity to **P**ressure on **L**ightness', range: '`0`..`1000` (per mille)' }],
	['`SPOi`', { name: '**S**ensitivity to **P**ressure on **O**pacity', range: '`0`..`1000` (per mille)' }],
	['`SPRi`', { name: '**S**ensitivity to **P**ressure on Scatte**r**', range: '`0`..`1000` (per mille)' }],
	['`SPSi`', { name: '**S**ensitivity to **P**ressure on **S**aturation', range: '`0`..`1000` (per mille)' }],
	['`SPZi`', { name: '**S**ensitivity to **P**ressure on Si**z**e', range: '`0`..`1000` (per mille)' }],
	['`SRAi`', { name: '**S**ensitivity to **R**andom on **A**ngle', range: '`0`..`1000` (per mille)' }],
	['`SRBi`', { name: '**S**ensitivity to **R**andom on **B**lackness', range: '`0`..`1000` (per mille)' }],
	['`SRHi`', { name: '**S**ensitivity to **R**andom on **H**ue', range: '`0`..`1000` (per mille)' }],
	['`SRLi`', { name: '**S**ensitivity to **R**andom on **L**ightness', range: '`0`..`1000` (per mille)' }],
	['`SROi`', { name: '**S**ensitivity to **R**andom on **O**pacity', range: '`0`..`1000` (per mille)' }],
	['`SRRi`', { name: '**S**ensitivity to **R**andom on Scatte**r**', range: '`0`..`1000` (per mille)' }],
	['`SRSi`', { name: '**S**ensitivity to **R**andom on **S**aturation', range: '`0`..`1000` (per mille)' }],
	['`SRZi`', { name: '**S**ensitivity to **R**andom on Si**z**e', range: '`0`..`1000` (per mille)' }],
	['`SSAi`', { name: '**S**ensitivity to **S**peed on **A**ngle', range: '`0`..`1000` (per mille)' }],
	['`SSBi`', { name: '**S**ensitivity to **S**peed on **B**lackness', range: '`0`..`1000` (per mille)' }],
	['`SSHi`', { name: '**S**ensitivity to **S**peed on **H**ue', range: '`0`..`1000` (per mille)' }],
	['`SSLi`', { name: '**S**ensitivity to **S**peed on **L**ightness', range: '`0`..`1000` (per mille)' }],
	['`SSOi`', { name: '**S**ensitivity to **S**peed on **O**pacity', range: '`0`..`1000` (per mille)' }],
	['`SSRi`', { name: '**S**ensitivity to **S**peed on Scatte**r**', range: '`0`..`1000` (per mille)' }],
	['`SSSi`', { name: '**S**ensitivity to **S**peed on **S**aturation', range: '`0`..`1000` (per mille)' }],
	['`SSZi`', { name: '**S**ensitivity to **S**peed on Si**z**e', range: '`0`..`1000` (per mille)' }],
	['`SVAi`', { name: '**S**ensitivity to **V**ertical on **A**ngle', range: '`0`..`1000` (per mille)' }],
	['`SVBi`', { name: '**S**ensitivity to **V**ertical on **B**lackness', range: '`0`..`1000` (per mille)' }],
	['`SVHi`', { name: '**S**ensitivity to **V**ertical on **H**ue', range: '`0`..`1000` (per mille)' }],
	['`SVLi`', { name: '**S**ensitivity to **V**ertical on **L**ightness', range: '`0`..`1000` (per mille)' }],
	['`SVOi`', { name: '**S**ensitivity to **V**ertical on **O**pacity', range: '`0`..`1000` (per mille)' }],
	['`SVRi`', { name: '**S**ensitivity to **V**ertical on Scatte**r**', range: '`0`..`1000` (per mille)' }],
	['`SVSi`', { name: '**S**ensitivity to **V**ertical on **S**aturation', range: '`0`..`1000` (per mille)' }],
	['`SVZi`', { name: '**S**ensitivity to **V**ertical on Si**z**e', range: '`0`..`1000` (per mille)' }],
	['`TA1i`', { name: '**T**ext **A**nti-Aliasing Sharpness', range: '`0`..`255`' }],
	['`TA2i`', { name: '**T**ext **A**nti-Aliasing Strength', range: '`0`..`255`' }],
	['`TAAi`', { name: '**T**ext **A**nti-**A**lias', values: new Map([[0, 'smooth / none'], [1, 'crisp'], [2, 'strong'], [3, 'system'], [4, 'custom']]) }],
	['`TALi`', {}],
	['`TAMi`', { name: '**T**ext **A**lign**m**ent', description: 'Controls text orientation when following a path.', values: new Map([[0, 'rotate'], [1, 'no rotate'], [2, 'skew vertical'], [3, 'skew horizontal']]) }],
	['`TAPv`', { name: '**T**ext **A**long **P**ath' }],
	['`TDTs`', { name: 'Cell (**TD**) **T**ext', range: false }],
	['`TFSv`', { name: '**T**ext **F**ormatted **S**tring', description: 'Contains a list of formatting operations and text runs.' }],
	['`TFTi`', { name: '**T**ext **F**low', values: new Map([[0, 'normal'], [1, 'fit to width (defined in [`BOAf`])'], [2, 'follow path'], [3, 'fit inside shape']]) }],
	['`TIAb`', {}],
	['`TIDi`', { name: '**T**ile **ID**', description: 'References a [`mkBT`] chunk tile by its ID', range: false }],
	['`TILv`', { name: '**T**ile **I**D **L**ist', description: 'An ordered list of tiles (or matte blocks) which combine to make the image or mask. The tiles are arranged left-to-right, top-to-bottom. The number of tiles per row can be calculated from the [`WPXi`] and [`TSZi`] values of the parent node. [`WPXi`] and [`HPXi`] can also be used to clip the right column and bottom row of tiles to the correct size.' }],
	['`TMCi`', { name: '**T**ile **M**atte **C**olour', description: 'Substitute for [`TIDi`] if only a solid colour is required for the tile area. Represents an ARGB colour.', range: '`0x00000000`..`0xffffffff`' }],
	['`TMOi`', { name: 'Menu Delay', description: 'Menu delay in milliseconds', range: false }],
	['`TOAf`', {}],
	['`TOPf`', { name: '**Top**', description: 'Distance (pixels) from top of container to top of entity.', range: false }],
	['`TOSi`', { name: '**T**ext Anti-Aliasing **S**amples', noValueDetails: true }],
	['`TOXf`', { name: '**T**exture **O**ffset **X**', range: false }],
	['`TOYf`', { name: '**T**exture **O**ffset **Y**', range: false }],
	['`TPWi`', { description: 'Not seen in Fireworks MX files. In Fireworks 8+, this seems to always be `0`', values: new Map([[0, 'unknown']]) }],
	['`TRMb`', { name: 'Export **Tr**i**m**med Images', range: false }],
	['`TRNs`', { name: '**T**ext **R**u**n**', description: 'Used for parts of text which share formatting options, and also used by [`BEHv`] for defining popup menus.', range: false }],
	['`TSLi`', { name: '**T**ype of **Sl**ice', values: new Map([[0, 'foreground'], [2, 'background']]) }],
	['`TSZi`', { name: '**T**ile **S**i**z**e', description: 'The size (width and height) of the [`mkBT`] tiles used in this image.', values: new Map([[128, 'tile is ARGB 128x128'], [256, 'tile is grayscale 256x256']]) }],
	['`TTDb`', { name: '**T**ooltip **T**racks **D**rag', description: 'Grab handle config controlled by `toolTipTracksDrag` in JavaScript.', values: new Map([
		[true, 'Tooltip remains visible while the handle is dragged, and updates its contents live'],
		[false, 'Tooltip disappears when the handle is dragged'],
	]) }],
	['`TTPs`', { name: '**T**ool**t**i**p**', details: 'Tooltip to display for this control point.', range: false }],
	['`TXBv`', { name: '**T**e**x**ture **B**rush' }],
	['`TXFv`', { name: '**T**e**x**ture **F**ill' }],
	['`TXTv`', { name: '**T**e**xt**', description: 'A text entity. The formatted text itself is defined in the [`TFSv`] subnode.' }],
	['`UIDs`', { name: '**U**nique **ID**', description: 'A UUID which is unique within the file. [`LSAv`] uses this to reference shared content defined in [`LSEv`] nodes.', range: false }],
	['`UNDb`', { name: '**Und**erline', values: new Map([[true, 'begin underline'], [false, 'end underline']]) }],
	['`UNMs`', { name: '**U**ser-facing **N**a**m**e', noValueDetails: true }],
	['`URLb`', { values: new Map([[false, 'Regular layer'], [true, 'Web Layer (slices)']]) }],
	['`URLv`', { name: 'Image Slice / Hotspot' }],
	['`URSi`', { name: '**UR**L Hotspot **S**hape', values: new Map([[0, 'rectangle'], [1, 'ellipse'], [2, 'polygon']]) }],
	['`VELf`', { name: '**Vel**ocity' }],
	['`VERi`', {}],
	['`VIFv`', { name: '**Vi**sibility per **F**rame', description: 'An ordered list of [`VISb`] nodes controlling this layer\'s visibility in each frame.' }],
	['`VISb`', { name: '**Vis**ible', range: false }],
	['`VRMi`', { description: 'Not seen in Fireworks 8 files.' }],
	['`VRSi`', { description: 'Not seen in Fireworks 8 files.' }],
	['`WIDf`', { name: '**Wid**th', description: 'The width of the document (pixels).', range: false }],
	['`WPXi`', { name: '**W**idth **P**i**x**els', description: 'The width of a raster image.', range: false }],
	['`XDAb`', { description: 'Something to do with the latest export settings (TODO)' }],
	['`XFMi`', {}],
	['`XFSi`', { name: 'E**x**port **F**ormat **S**election', description: 'The last used format for exporting.', values: new Map([
		[0, 'PDF'],
		[1, 'HTML and Images'],
		[2, 'Images'],
		[4, 'Director'],
		[5, 'CSS and Images'],
		[6, 'Layers'],
		[7, 'States'],
		[8, 'Pages'],
		[9, 'MXML and Images'],
		[10, 'Lotus Domino Designer'],
	]) }],
	['`XLCf`', { name: '**X** **L**o**c**ation', range: false }],
	['`XMDi`', { description: 'Something to do with the latest export settings (TODO)' }],
	['`XOFf`', { name: '**X** **Of**fset', range: '`0`..`100` (hundredths of a pixel?)' }],
	['`XPCf`', { name: '**X** **P**rimary **C**ontrol', range: false }],
	['`XSCf`', { name: '**X** **S**econdary **C**ontrol', range: false }],
	['`XSLf`', {}],
	['`XSZi`', { name: 'Export **X** **S**i**z**e', description: 'Width (in pixels) of the exported image, if [`CNSi`] is `true`.', range: false }],
	['`XTMi`', { name: '**X**H**TM**L', values: new Map([[0, 'Export with HTML syntax'], [1, 'Export with XHTML syntax']]) }],
	['`YLCf`', { name: '**Y** **L**o**c**ation', range: false }],
	['`YOFf`', { name: '**Y** **Of**fset', range: '`0`..`100` (hundredths of a pixel?)' }],
	['`YPCf`', { name: '**Y** **P**rimary **C**ontrol', range: false }],
	['`YSCf`', { name: '**Y** **S**econdary **C**ontrol', range: false }],
	['`YSLf`', {}],
	['`YSZi`', { name: 'Export **Y** **S**i**z**e', description: 'Height (in pixels) of the exported image, if [`CNSi`] is `true`.', range: false }],
	['`ZSFi`', {}],
	['`ZSLv`', {}],
	['`ZSNs`', {}],
	['`ZSOi`', {}],
	['`ZSTv`', {}],
]);
